name: Test against RabbitMQ 3.11 alpha

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [new_client_snapshot]

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      rabbitmq:
        image: pivotalrabbitmq/rabbitmq-dev:3.11
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Enable JMS topic exchange plugin
        run: docker exec ${{job.services.rabbitmq.id}} rabbitmq-plugins enable rabbitmq_jms_topic_exchange --offline
      - name: Stop RabbitMQ application
        run: docker exec ${{job.services.rabbitmq.id}} rabbitmqctl stop_app
      - name: Start RabbitMQ application
        run: docker exec ${{job.services.rabbitmq.id}} rabbitmqctl start_app
      - name: Output dependencies
        run: ./mvnw dependency:tree --no-transfer-progress
      - name: Test
        run: ./mvnw clean verify --no-transfer-progress